title: heavy`s blog
description: Blog about Front-end, web perfomance, computer scince & more
author: Casper Søkol
baseurl: "" 
url: "" 

telegram_username: itsheavy
github_username:  j-heavy

markdown: kramdown