title: heavy`s blog
description: Blog about Front-end, web perfomance, computer science & more
author: Casper Søkol
baseurl: "" 
url: "" 

telegram_username: itsheavy
github_username:  j-heavy

markdown: kramdown

plugins:
  - jekyll-minifier

jekyll-minifier:
  preserve_php: true                
  remove_spaces_inside_tags: true   
  remove_multi_spaces: true         
  remove_comments: true             
  remove_intertag_spaces: true      
  remove_quotes: false              
  compress_css: true                
  compress_javascript: true         
  simple_doctype: false             
  remove_script_attributes: false   
  remove_style_attributes: false    
  remove_link_attributes: false     
  remove_form_attributes: false     
  remove_input_attributes: false    
  remove_javascript_protocol: false 
  remove_http_protocol: false       
  remove_https_protocol: false      
  preserve_line_breaks: false       
  simple_boolean_attributes: false  
  compress_js_templates: true      

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all